apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mi-mysql
spec:
  selector:
    matchLabels:
      app: mi-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mi-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mi-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_USER
          value: usuario
        - name: MYSQL_DATABASE
          value: foo
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql

